[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

# export NDK_ROOT="/usr/local/Cellar/android-ndk/r10e"

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
export PATH="/usr/local/sbin:$PATH"
export PATH="/Users/jonjon/.docker:$PATH"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"

##
# asdf manager setup
#
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

##
# Use gnu-sed as sed
#
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jonjon/repos/google-cloud-sdk/path.bash.inc' ]; then source '/Users/jonjon/repos/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jonjon/repos/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/jonjon/repos/google-cloud-sdk/completion.bash.inc'; fi

# Add code command for VSCode
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="$PATH:/usr/local/opt/openssl/bin:$HOME/repos/click"
